name = "cf-manager"
compatibility_date = "2024-12-01"
main = "src/index.ts"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "cfmgr"
database_id = "13b75013-7332-4bd0-9323-7e50c9e6ea52"

[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_NAMESPACE_ID"

[vars]
API_SECRET = "sk-zhi"
ENCRYPTION_KEY = "sk-zhi"
DEMO_ACCOUNT_IDS = ""
